[package]
name = "blissb"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
tiny-keccak = "1.1"

[features]
default = [ "iv" ]
o = []
i = []
ii = []
iii = []
iv = []
